export const demoConversation = {
  prompt: 'Who is the best hockey player?',
  responseLabel: 'Generated Response (Click Token to see other Tokens Considered):',
  tokens: [
    {
      id: 0,
      text: 'Wayne',
      confidence: 0.93,
      alternatives: [
        { token: 'Mario', prob: 0.03 },
        { token: 'Sidney', prob: 0.02 },
        { token: 'Connor', prob: 0.015 },
        { token: 'Gordie', prob: 0.01 },
        { token: 'Bobby', prob: 0.008 },
        { token: 'Alex', prob: 0.006 },
        { token: 'Jaromir', prob: 0.004 },
        { token: 'Patrick', prob: 0.003 },
        { token: 'Mark', prob: 0.002 },
        { token: 'Steve', prob: 0.001 }
      ],
    },
    {
      id: 1,
      text: 'Gretzky',
      confidence: 0.97,
      alternatives: [
        { token: 'Lemieux', prob: 0.01 },
        { token: 'Crosby', prob: 0.007 },
        { token: 'McDavid', prob: 0.005 },
        { token: 'Howe', prob: 0.004 },
        { token: 'Orr', prob: 0.003 },
        { token: 'Ovechkin', prob: 0.002 },
        { token: 'Jagr', prob: 0.0015 },
        { token: 'Yzerman', prob: 0.0012 },
        { token: 'Messier', prob: 0.001 },
        { token: 'Sakic', prob: 0.0008 }
      ],
    },
    {
      id: 2,
      text: 'remains',
      confidence: 0.73,
      alternatives: [
        { token: 'is', prob: 0.12 },
        { token: 'stands', prob: 0.06 },
        { token: 'continues', prob: 0.03 },
        { token: 'appears', prob: 0.02 },
        { token: 'seems', prob: 0.015 },
        { token: 'stays', prob: 0.012 },
        { token: 'was', prob: 0.01 },
        { token: 'looks', prob: 0.008 },
        { token: 'feels', prob: 0.006 },
        { token: 'has', prob: 0.005 }
      ],
    },
    {
      id: 3,
      text: 'the',
      confidence: 0.99,
      alternatives: [
        { token: 'a', prob: 0.004 },
        { token: 'an', prob: 0.002 },
        { token: 'this', prob: 0.0015 },
        { token: 'that', prob: 0.0012 },
        { token: 'his', prob: 0.001 },
        { token: 'their', prob: 0.0008 },
        { token: 'our', prob: 0.0006 },
        { token: 'its', prob: 0.0005 },
        { token: 'one', prob: 0.0004 },
        { token: 'any', prob: 0.0003 }
      ],
    },
    {
      id: 4,
      text: 'undisputed',
      confidence: 0.82,
      alternatives: [
        { token: 'clear', prob: 0.05 },
        { token: 'obvious', prob: 0.03 },
        { token: 'definitive', prob: 0.025 },
        { token: 'unquestioned', prob: 0.02 },
        { token: 'recognized', prob: 0.015 },
        { token: 'accepted', prob: 0.012 },
        { token: 'widely-known', prob: 0.01 },
        { token: 'dominant', prob: 0.008 },
        { token: 'strong', prob: 0.006 },
        { token: 'leading', prob: 0.005 }
      ],
    },
    {
      id: 5,
      text: '"Greatest',
      confidence: 0.89,
      alternatives: [
        { token: '"Best', prob: 0.04 },
        { token: '"Top', prob: 0.025 },
        { token: '"Most', prob: 0.015 },
        { token: '"Ultimate', prob: 0.01 },
        { token: '"Legendary', prob: 0.008 },
        { token: '"Finest', prob: 0.006 },
        { token: '"Elite', prob: 0.005 },
        { token: '"Supreme', prob: 0.004 },
        { token: '"GOAT', prob: 0.003 },
        { token: '"Historic', prob: 0.002 }
      ],
    },
    {
      id: 6,
      text: 'of',
      confidence: 0.98,
      alternatives: [
        { token: 'in', prob: 0.006 },
        { token: 'among', prob: 0.004 },
        { token: 'for', prob: 0.003 },
        { token: 'through', prob: 0.002 },
        { token: 'within', prob: 0.0015 },
        { token: 'from', prob: 0.0012 },
        { token: 'by', prob: 0.001 },
        { token: 'over', prob: 0.0008 },
        { token: 'around', prob: 0.0006 },
        { token: 'under', prob: 0.0005 }
      ],
    },
    {
      id: 7,
      text: 'All',
      confidence: 0.96,
      alternatives: [
        { token: 'Time', prob: 0.012 },
        { token: 'Them', prob: 0.006 },
        { token: 'History', prob: 0.004 },
        { token: 'Players', prob: 0.003 },
        { token: 'Greats', prob: 0.0025 },
        { token: 'Eras', prob: 0.002 },
        { token: 'Sports', prob: 0.0015 },
        { token: 'Legends', prob: 0.0012 },
        { token: 'Years', prob: 0.001 },
        { token: 'Generations', prob: 0.0008 }
      ],
    },
    {
      id: 8,
      text: 'Time,"',
      confidence: 0.95,
      alternatives: [
        { token: 'History,"', prob: 0.015 },
        { token: 'Hockey,"', prob: 0.008 },
        { token: 'Era,"', prob: 0.006 },
        { token: 'Generations,"', prob: 0.004 },
        { token: 'Players,"', prob: 0.003 },
        { token: 'Seasons,"', prob: 0.0025 },
        { token: 'Sport,"', prob: 0.002 },
        { token: 'League,"', prob: 0.0015 },
        { token: 'Record,"', prob: 0.0012 },
        { token: 'Game,"', prob: 0.001 }
      ],
    },
    {
      id: 9,
      text: 'holding',
      confidence: 0.66,
      alternatives: [
        { token: 'owning', prob: 0.11 },
        { token: 'with', prob: 0.07 },
        { token: 'maintaining', prob: 0.04 },
        { token: 'having', prob: 0.03 },
        { token: 'keeping', prob: 0.02 },
        { token: 'possessing', prob: 0.015 },
        { token: 'carrying', prob: 0.012 },
        { token: 'retaining', prob: 0.01 },
        { token: 'posting', prob: 0.008 },
        { token: 'recording', prob: 0.006 }
      ],
    },
    {
      id: 10,
      text: '61',
      confidence: 0.91,
      alternatives: [
        { token: '62', prob: 0.03 },
        { token: '60', prob: 0.02 },
        { token: '59', prob: 0.01 },
        { token: '58', prob: 0.008 },
        { token: '63', prob: 0.007 },
        { token: '64', prob: 0.006 },
        { token: '57', prob: 0.005 },
        { token: '65', prob: 0.004 },
        { token: '56', prob: 0.003 },
        { token: '66', prob: 0.002 }
      ],
    },
    {
      id: 11,
      text: 'NHL',
      confidence: 0.94,
      alternatives: [
        { token: 'league', prob: 0.025 },
        { token: 'hockey', prob: 0.015 },
        { token: 'National', prob: 0.01 },
        { token: 'professional', prob: 0.008 },
        { token: 'modern', prob: 0.006 },
        { token: 'North', prob: 0.005 },
        { token: 'major', prob: 0.004 },
        { token: 'sport', prob: 0.003 },
        { token: 'ice', prob: 0.002 },
        { token: 'elite', prob: 0.0015 }
      ],
    },
    {
      id: 12,
      text: 'records',
      confidence: 0.88,
      alternatives: [
        { token: 'marks', prob: 0.04 },
        { token: 'milestones', prob: 0.025 },
        { token: 'achievements', prob: 0.02 },
        { token: 'stats', prob: 0.015 },
        { token: 'titles', prob: 0.01 },
        { token: 'numbers', prob: 0.008 },
        { token: 'figures', prob: 0.006 },
        { token: 'honors', prob: 0.005 },
        { token: 'benchmarks', prob: 0.004 },
        { token: 'accomplishments', prob: 0.003 }
      ],
    },
    {
      id: 13,
      text: 'including',
      confidence: 0.72,
      alternatives: [
        { token: 'with', prob: 0.09 },
        { token: 'such', prob: 0.05 },
        { token: 'featuring', prob: 0.03 },
        { token: 'covering', prob: 0.02 },
        { token: 'spanning', prob: 0.015 },
        { token: 'like', prob: 0.012 },
        { token: 'among', prob: 0.01 },
        { token: 'notably', prob: 0.008 },
        { token: 'containing', prob: 0.006 },
        { token: 'listing', prob: 0.005 }
      ],
    },
    {
      id: 14,
      text: 'the',
      confidence: 0.99,
      alternatives: [
        { token: 'a', prob: 0.004 },
        { token: 'his', prob: 0.002 },
        { token: 'this', prob: 0.0015 },
        { token: 'their', prob: 0.0012 },
        { token: 'an', prob: 0.001 },
        { token: 'its', prob: 0.0008 },
        { token: 'our', prob: 0.0006 },
        { token: 'one', prob: 0.0005 },
        { token: 'that', prob: 0.0004 },
        { token: 'any', prob: 0.0003 }
      ],
    },
    {
      id: 15,
      text: 'most',
      confidence: 0.84,
      alternatives: [
        { token: 'highest', prob: 0.05 },
        { token: 'greatest', prob: 0.03 },
        { token: 'largest', prob: 0.025 },
        { token: 'best', prob: 0.02 },
        { token: 'top', prob: 0.015 },
        { token: 'leading', prob: 0.012 },
        { token: 'record', prob: 0.01 },
        { token: 'career', prob: 0.008 },
        { token: 'all-time', prob: 0.006 },
        { token: 'overall', prob: 0.005 }
      ],
    },
    {
      id: 16,
      text: 'career',
      confidence: 0.79,
      alternatives: [
        { token: 'total', prob: 0.07 },
        { token: 'overall', prob: 0.04 },
        { token: 'lifetime', prob: 0.03 },
        { token: 'professional', prob: 0.025 },
        { token: 'historic', prob: 0.015 },
        { token: 'long-term', prob: 0.012 },
        { token: 'full', prob: 0.01 },
        { token: 'record', prob: 0.008 },
        { token: 'complete', prob: 0.006 },
        { token: 'league', prob: 0.005 }
      ],
    },
    {
      id: 17,
      text: 'goals,',
      confidence: 0.15,
      alternatives: [
        { token: 'assists,', prob: 0.10 },
        { token: 'points,', prob: 0.03 },
        { token: 'and', prob: 0.009 },
        { token: 'records,', prob: 0.006 },
        { token: 'titles,', prob: 0.005 },
        { token: 'trophies,', prob: 0.004 },
        { token: 'wins,', prob: 0.0035 },
        { token: 'milestones,', prob: 0.003 },
        { token: 'honors,', prob: 0.0025 },
        { token: 'achievements,', prob: 0.002 }
      ],
    },
    {
      id: 18,
      text: 'assists,',
      confidence: 0.81,
      alternatives: [
        { token: 'points,', prob: 0.06 },
        { token: 'goals,', prob: 0.045 },
        { token: 'passes,', prob: 0.02 },
        { token: 'records,', prob: 0.015 },
        { token: 'plays,', prob: 0.012 },
        { token: 'setups,', prob: 0.01 },
        { token: 'chances,', prob: 0.008 },
        { token: 'feeds,', prob: 0.006 },
        { token: 'touches,', prob: 0.005 },
        { token: 'drives,', prob: 0.004 }
      ],
    },
    {
      id: 19,
      text: 'and',
      confidence: 0.98,
      alternatives: [
        { token: 'with', prob: 0.006 },
        { token: 'plus', prob: 0.004 },
        { token: 'along', prob: 0.003 },
        { token: 'as', prob: 0.002 },
        { token: 'while', prob: 0.0015 },
        { token: 'also', prob: 0.0012 },
        { token: 'combined', prob: 0.001 },
        { token: 'together', prob: 0.0008 },
        { token: 'or', prob: 0.0006 },
        { token: 'including', prob: 0.0005 }
      ],
    },
    {
      id: 20,
      text: 'points.',
      confidence: 0.87,
      alternatives: [
        { token: 'totals.', prob: 0.04 },
        { token: 'records.', prob: 0.025 },
        { token: 'stats.', prob: 0.02 },
        { token: 'milestones.', prob: 0.015 },
        { token: 'goals.', prob: 0.01 },
        { token: 'assists.', prob: 0.008 },
        { token: 'numbers.', prob: 0.006 },
        { token: 'achievements.', prob: 0.005 },
        { token: 'honors.', prob: 0.004 },
        { token: 'figures.', prob: 0.003 }
      ],
    },
  ],
};
